
=== Vulkan support

[small]#Rfr: link:http://www.glfw.org/docs/latest/group__vulkan.html[Vulkan reference].#

[[vulkan_supported]]
* _boolean_ = *vulkan_supported*( ) +
[small]#Returns _true_ if MoonGLFW was built with Vulkan support, false otherwise.#

[[get_required_instance_extensions]]
* _extensions_ = *get_required_instance_extensions*( ) +
[small]#Returns a table containing the names (strings) of the extensions needed to create Vulkan surfaces
for GLFW windows. +
The returned extensions must be enabled for the affected Vulkan instance before creating a surface
with <<create_window_surface, create_window_surface>>(&nbsp;).#

[[get_physical_device_presentation_support]]
* _boolean_ = *get_physical_device_presentation_support*(_instanceRAW_, _physdevRAW_, _queuefamily_) +
[small]#Returns _true_ if the specified queue family for the specified physical device supports
presentation to the platform GLFW was built for. +
The _instanceRAW_ parameter (integer) must be a valid VkInstance handle. +
The _physdevRAW_ parameter (integer) must be a valid VkPhysicalDevice handle.#


[[create_window_surface]]
* _surfaceRAW_ = *create_window_surface*(_window_, _instanceRAW_, [_allocatorLUD_]) +
[small]#Creates a surface for the specified _window_, and returns its VkSurfaceKHR handle as an integer. +
The _instanceRAW_ parameter (integer) must be a valid VkInstance handle. +
The _allocatorLUD_ optional parameter (lightuserdata), is the pass:[VkAllocationCallbacks*] allocator to be used when creating the surface. If not given, _NULL_ will be used.#

////
[[destroy_surface]]
* *destroy_surface*(_instanceRAW_, _surfaceRAW_, [_allocatorLUD_]) +
[small]#Binding to the vkDestroySurface(&nbsp;) function of the Vulkan API.#
////

IMPORTANT: MoonGLFW assumes that the raw Vulkan handles (RAW) and lightuserdata (LUD) passed as 
parameters to its functions actually are what they are meant to be, and has no means to verify it.


